### PR TITLE
Change surfacelocater.h

### PR DESCRIPTION
**Pull request by KatyT12**
When trying to build planet-server I got errors about multiple definitions of getSurfaceFromLocator and getSurfaceFromJson and when making them inline it built fine

### CODE REVIEW

**Comment by Jachdich** [comment]
yo thanks, I didn't notice that, will merge

**Comment by Jachdich** [comment]
Also, I had a look at your repository https://github.com/open-source-KT/random2D-planet. The planets you have there look a lot better than mine, and I'm wondering what exactly is different? Could it simply be the difference between simplex noise and perlin noise? anyway thanks again for this fix, it's very useful.

**Comment by KatyT12** [comment]
The quality of the planets is quite subjective since I think the colors of your planets blend together much better while mine are just random. Your planets do also look more consistently good while mine can look good but some end up being just one solid color with like a tiny spec of another random color.

Sometimes you can see directional artifacts in my planets which is a problem with perlinoise which your planets don't really have.
The different noise algorithms definitely play a part but it could be differences in set variables for the algorithms.

The difference in noise may also be the number of octaves since in my program the planets are quite large I can have quite a few octaves which can give more detail to the planets but if I were to make them smaller like they are in the solar systems in your planet game too many octaves will give floating point errors and the game will crash.

The FastNoise class you are using allows you to set the amount of octaves and other variables like the bias that affect the noise algorithm you could perhaps have that be randomly generated within a range if you wanted to vary the detail of the noise in your planets more.

**Comment by Jachdich** [comment]
You mention about octaves - I think that's the thing. A lot of my planets seem to have rather uninteresting patterns with smooth edges, which I think could be improved with octaves.

**Comment by KatyT12** [comment]
Yes, the more octaves the more detail the planets will have. Make sure to test out the octaves on the planets since too many octaves on small buffers will divide too much to where it becomes zero and you will get a floating point error.

Bias/smoothness is also something you can configure the Perlin noise algorithm with where the lower the bias the less smoother it is, I'm not entirely sure about simplex noise because I haven't tried it but there is probably something similar where you can configure how smooth the noise is.

The FastNoise class has a lot of getters and setters for different variables for the noise algorithm so you could test out them too :)

**Comment by Jachdich** [comment]
Right - I'll beware of that, thanks for the heads up. It does seem that the FastNoise library has lots of useful features, I'll have to look into that in more detail.

**Pull request merged**
